backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Subtítulo", name: "subtitle", widget: "string", required: false }
      - { label: "Contenido", name: "body", widget: "markdown" }

  - name: "data"
    label: "Datos"
    files:
      - name: "media"
        label: "Apariciones en medios"
        file: "data/media.json"
        fields:
          - name: "items"
            label: "Apariciones"
            widget: "list"
            fields:
              - { label: "Título", name: "title", widget: "string" }
              - { label: "Medio", name: "source", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
